name: 'Continuous Delivery'

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          project_id: latam-mle-challenge-437122
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Build and push Docker image to GCR
        run: |
          docker build -t gcr.io/latam-mle-challenge-437122/flight-api:latest .
          docker push gcr.io/latam-mle-challenge-437122/flight-api:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flight-api \
            --image gcr.io/latam-mle-challenge-437122/flight-api:latest \
            --platform managed \
            --region southamerica-east1 \
            --allow-unauthenticated \
            --memory 1Gi
